-- Schema DDL para o Jogo da Velha WS3 (SQLite / PostgreSQL / MySQL)

CREATE TABLE IF NOT EXISTS JOGADOR (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nickname VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SALA_JOGO (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    codigo VARCHAR(10) UNIQUE NOT NULL,
    nome VARCHAR(100) NOT NULL,
    status VARCHAR(20) DEFAULT 'AGUARDANDO', -- AGUARDANDO, EM_JOGO, FINALIZADA
    criador_id INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (criador_id) REFERENCES JOGADOR(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PARTIDA (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sala_id INTEGER NOT NULL,
    jogador_x_id INTEGER,
    jogador_o_id INTEGER,
    vencedor_id INTEGER, -- NULL se empate ou em andamento
    status VARCHAR(20) DEFAULT 'EM_ANDAMENTO', -- EM_ANDAMENTO, FINALIZADA, EMPATE
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sala_id) REFERENCES SALA_JOGO(id) ON DELETE CASCADE,
    FOREIGN KEY (jogador_x_id) REFERENCES JOGADOR(id),
    FOREIGN KEY (jogador_o_id) REFERENCES JOGADOR(id),
    FOREIGN KEY (vencedor_id) REFERENCES JOGADOR(id)
);

CREATE TABLE IF NOT EXISTS JOGADA (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    partida_id INTEGER NOT NULL,
    jogador_id INTEGER NOT NULL,
    posicao INTEGER NOT NULL, -- 0 a 8
    simbolo VARCHAR(1) NOT NULL, -- X ou O
    numero_jogada INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (partida_id) REFERENCES PARTIDA(id) ON DELETE CASCADE,
    FOREIGN KEY (jogador_id) REFERENCES JOGADOR(id)
);

CREATE TABLE IF NOT EXISTS MENSAGEM_CHAT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sala_id INTEGER NOT NULL,
    jogador_id INTEGER NOT NULL,
    mensagem TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sala_id) REFERENCES SALA_JOGO(id) ON DELETE CASCADE,
    FOREIGN KEY (jogador_id) REFERENCES JOGADOR(id)
);
